apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: laravel-app

resources:
- ../../base
- ../../database
- hpa.yaml

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: your-registry/laravel-app
  newTag: v1.0.0
